AWSTemplateFormatVersion: 2010-09-09
Description: VPC template for Project X

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VPCID
      - PublicSubnet1Id
      - PublicSubnet2Id
      - PublicSubnet3Id
      - PrivateSubnet1Id
      - PrivateSubnet2Id
      - PrivateSubnet3Id
      - BastionSecurityGroup
      - KeyPairName
      - ALBAccessCIDR
      - AgilePartnerCert
    ParameterLabels:
      VPCID:
        default: VPC ID
      PublicSubnet1Id:
        default: Public subnet 1 ID
      Public subnet 2 ID:
        default: Public subnet 2 ID
      Public subnet 3 ID:
        default: Public subnet 3 ID
      PrivateSubnet1Id:
        default: Private subnet 1 ID
      Private subnet 2 ID:
        default: Private subnet 2 ID
      Private subnet 3 ID:
        default: Private subnet 3 ID
      BastionSecurityGroup:
        default: Bastion security group ID
      KeyPairName:
        default: Key pair name
      ALBAccessCIDR:
        default: ALB access CIDR
      AgilePartnerCert:
        default: Valid SSL certificate

Parameters:
  VPCID:
    Description: A VPC ID
    Type: String
  PublicSubnet1Id:
    Description: public DMZ subnet 1 ID located in Availability Zone 1
    Type: String
  PublicSubnet2Id:
    Description: public DMZ subnet 2 ID located in Availability Zone 2
    Type: String
  PublicSubnet3Id:
    Description: public DMZ subnet 3 ID located in Availability Zone 3
    Type: String
  PrivateSubnet1Id:
    Description: private DMZ subnet 1 ID located in Availability Zone 1
    Type: String
  PrivateSubnet2Id:
    Description: private DMZ subnet 2 ID located in Availability Zone 2
    Type: String
  PrivateSubnet3Id:
    Description: private DMZ subnet 3 ID located in Availability Zone 3
    Type: String
  BastionSecurityGroup:
    Description: Bastion security group ID
    Type: String
  KeyPairName: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be a valid Key Pair
  ALBAccessCIDR:
    Description: ALB access CIDR
    Type: String
    Default: 0.0.0.0/0
  AgilePartnerCert:
    Description: Agile Partner SSL Certificate ARN
    Type: String
    ConstraintDescription: must be a valid Certificate ARN

Resources:
  PrivateHostSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPCID
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          SourceSecurityGroupId: !Ref BastionSecurityGroup
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: ProjectXPrivateHostSG

  DeployAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0172c7e8739ccb954
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups:
        - !Ref PrivateHostSecurityGroup
            
  DeployAppASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
        - !Ref PrivateSubnet3Id
      DesiredCapacity: 1
      LaunchConfigurationName: !Ref DeployAppLaunchConfig
      TargetGroupARNs:
        - !Ref WebAppTargetGroup
        - !Ref WebAppSecureTargetGroup
      MaxSize: 2
      MinSize: 1
      Tags:
          - Key: Name
            Value: ProjectXASG
            PropagateAtLaunch: True
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: True

  ALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPCID
      GroupDescription: Enable HTTP/HTTPS access
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '80'
          ToPort: '80'
          CidrIp: !Ref ALBAccessCIDR
        - IpProtocol: 'tcp'
          FromPort: '443'
          ToPort: '443'
          CidrIp: !Ref ALBAccessCIDR
      Tags:
        - Key: Name
          Value: ProjectXALBSG

  WebAppALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
        - !Ref PublicSubnet3Id
      Tags:
        - Key: Name
          Value: ProjectXALB
      Type: application
  
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppALB
      Port: '80'
      Protocol: HTTP

  SecureListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: WebAppSecureTargetGroup
      LoadBalancerArn:
        Ref: WebAppALB
      Port: '443'
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AgilePartnerCert

  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: '80'
      Protocol: 'HTTP'
      VpcId: !Ref VPCID
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: ProjectXWebAppTG

  WebAppSecureTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: '443'
      Protocol: 'HTTPS'
      VpcId: !Ref VPCID
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: 443
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: ProjectXSecureTG

Outputs:
  ProjectXALBDNS:
    Description: Web App ALB DNS Name 
    Value:
      Fn::Join:
        - ''
        - - "http://"
          - Fn::GetAtt: WebAppALB.DNSName